// Generated by mcp__supabase__generate_typescript_types.
// Regenerate after any schema migration.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: '14.5'
  }
  public: {
    Tables: {
      preferences: {
        Row: {
          days_per_week: number | null
          equipment: string[]
          experience_level: string
          focus_muscles: string[]
          goals: string[]
          id: string
          limitations: string | null
          session_length_min: number | null
          updated_at: string
          user_id: string
        }
        Insert: {
          days_per_week: number | null
          equipment?: string[]
          experience_level: string
          focus_muscles?: string[]
          goals: string[]
          id?: string
          limitations?: string | null
          session_length_min: number | null
          updated_at?: string
          user_id: string
        }
        Update: {
          days_per_week?: number | null
          equipment?: string[]
          experience_level?: string
          focus_muscles?: string[]
          goals?: string[]
          id?: string
          limitations?: string | null
          session_length_min?: number | null
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: 'preferences_user_id_fkey'
            columns: ['user_id']
            isOneToOne: true
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
        ]
      }
      profiles: {
        Row: {
          created_at: string
          display_name: string | null
          id: string
          onboarded_at: string | null
          unit_preference: string
        }
        Insert: {
          created_at?: string
          display_name?: string | null
          id: string
          onboarded_at?: string | null
          unit_preference?: string
        }
        Update: {
          created_at?: string
          display_name?: string | null
          id?: string
          onboarded_at?: string | null
          unit_preference?: string
        }
        Relationships: []
      }
      routine_days: {
        Row: {
          day_of_week: number
          id: string
          is_rest_day: boolean
          name: string
          routine_id: string
        }
        Insert: {
          day_of_week: number
          id?: string
          is_rest_day?: boolean
          name: string
          routine_id: string
        }
        Update: {
          day_of_week?: number
          id?: string
          is_rest_day?: boolean
          name?: string
          routine_id?: string
        }
        Relationships: [
          {
            foreignKeyName: 'routine_days_routine_id_fkey'
            columns: ['routine_id']
            isOneToOne: false
            referencedRelation: 'routines'
            referencedColumns: ['id']
          },
        ]
      }
      routine_exercises: {
        Row: {
          exercise_name: string
          id: string
          metric: string
          notes: string | null
          order_index: number
          rest_seconds: number | null
          routine_day_id: string
          target_reps: number
          target_seconds: number | null
          target_sets: number
          target_weight: number | null
        }
        Insert: {
          exercise_name: string
          id?: string
          metric?: string
          notes?: string | null
          order_index?: number
          rest_seconds?: number | null
          routine_day_id: string
          target_reps?: number
          target_seconds?: number | null
          target_sets?: number
          target_weight?: number | null
        }
        Update: {
          exercise_name?: string
          id?: string
          metric?: string
          notes?: string | null
          order_index?: number
          rest_seconds?: number | null
          routine_day_id?: string
          target_reps?: number
          target_seconds?: number | null
          target_sets?: number
          target_weight?: number | null
        }
        Relationships: [
          {
            foreignKeyName: 'routine_exercises_routine_day_id_fkey'
            columns: ['routine_day_id']
            isOneToOne: false
            referencedRelation: 'routine_days'
            referencedColumns: ['id']
          },
        ]
      }
      routines: {
        Row: {
          created_at: string
          generated_by_model: string | null
          generation_prompt_version: string | null
          id: string
          user_id: string
          week_start_date: string
        }
        Insert: {
          created_at?: string
          generated_by_model?: string | null
          generation_prompt_version?: string | null
          id?: string
          user_id: string
          week_start_date: string
        }
        Update: {
          created_at?: string
          generated_by_model?: string | null
          generation_prompt_version?: string | null
          id?: string
          user_id?: string
          week_start_date?: string
        }
        Relationships: [
          {
            foreignKeyName: 'routines_user_id_fkey'
            columns: ['user_id']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
        ]
      }
      session_sets: {
        Row: {
          completed: boolean
          exercise_name: string
          id: string
          order_index: number
          reps: number | null
          seconds: number | null
          session_id: string
          set_index: number
          weight: number | null
        }
        Insert: {
          completed?: boolean
          exercise_name: string
          id?: string
          order_index?: number
          reps?: number | null
          seconds?: number | null
          session_id: string
          set_index: number
          weight?: number | null
        }
        Update: {
          completed?: boolean
          exercise_name?: string
          id?: string
          order_index?: number
          reps?: number | null
          seconds?: number | null
          session_id?: string
          set_index?: number
          weight?: number | null
        }
        Relationships: [
          {
            foreignKeyName: 'session_sets_session_id_fkey'
            columns: ['session_id']
            isOneToOne: false
            referencedRelation: 'workout_sessions'
            referencedColumns: ['id']
          },
        ]
      }
      workout_sessions: {
        Row: {
          completed_at: string | null
          id: string
          name: string | null
          performed_on: string
          routine_day_id: string | null
          started_at: string
          total_volume: number
          user_id: string
        }
        Insert: {
          completed_at?: string | null
          id?: string
          name?: string | null
          performed_on?: string
          routine_day_id?: string | null
          started_at?: string
          total_volume?: number
          user_id: string
        }
        Update: {
          completed_at?: string | null
          id?: string
          name?: string | null
          performed_on?: string
          routine_day_id?: string | null
          started_at?: string
          total_volume?: number
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: 'workout_sessions_routine_day_id_fkey'
            columns: ['routine_day_id']
            isOneToOne: false
            referencedRelation: 'routine_days'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'workout_sessions_user_id_fkey'
            columns: ['user_id']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
        ]
      }
    }
    Views: { [_ in never]: never }
    Functions: {
      reset_training_data: {
        Args: never
        Returns: undefined
      }
      reset_weekly_plan_to_empty: {
        Args: { p_week_start_date: string }
        Returns: string
      }
      save_weekly_routine: {
        Args: {
          p_days: Json
          p_generated_by_model: string
          p_generation_prompt_version: string
          p_week_start_date: string
        }
        Returns: string
      }
    }
    Enums: { [_ in never]: never }
    CompositeTypes: { [_ in never]: never }
  }
}

type PublicSchema = Database['public']

export type Tables<T extends keyof PublicSchema['Tables']> =
  PublicSchema['Tables'][T]['Row']
export type TablesInsert<T extends keyof PublicSchema['Tables']> =
  PublicSchema['Tables'][T]['Insert']
export type TablesUpdate<T extends keyof PublicSchema['Tables']> =
  PublicSchema['Tables'][T]['Update']
